services:
    phpbb.skeleton.collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: phpbb.skeleton.ext.skeleton }

    phpbb.skeleton.ext.skeleton.phplistener:
        class: phpbb\skeleton\skeleton
        arguments:
            - 'phplistener'
            - true
            - []
            - ['config/services.yml', 'event/main_listener.php']
        tags:
            - { name: phpbb.skeleton.ext.skeleton }

    phpbb.skeleton.ext.skeleton.htmllistener:
        class: phpbb\skeleton\skeleton
        arguments:
            - 'htmllistener'
            - true
            - []
            - ['styles/prosilver/template/event/overall_header_navigation_prepend.html']
        tags:
            - { name: phpbb.skeleton.ext.skeleton }

    phpbb.skeleton.ext.skeleton.acp:
        class: phpbb\skeleton\skeleton
        arguments:
            - 'acp'
            - true
            - []
            - ['acp/main_info.php', 'acp/main_module.php', 'adm/style/demo_body.html', 'language/en/info_acp_demo.php']
        tags:
            - { name: phpbb.skeleton.ext.skeleton }

    phpbb.skeleton.ext.skeleton.migration:
        class: phpbb\skeleton\skeleton
        arguments:
            - 'migration'
            - true
            - []
            - ['migrations/release_1_0_0.php', 'migrations/release_1_0_1.php']
        tags:
            - { name: phpbb.skeleton.ext.skeleton }

    phpbb.skeleton.ext.skeleton.service:
        class: phpbb\skeleton\skeleton
        arguments:
            - 'service'
            - true
            - []
            - ['service.php', 'config/services.yml', 'config/parameters.yml']
        tags:
            - { name: phpbb.skeleton.ext.skeleton }

    phpbb.skeleton.ext.skeleton.controller:
        class: phpbb\skeleton\skeleton
        arguments:
            - 'controller'
            - true
            - []
            - ['config/routing.yml', 'config/services.yml', 'event/main_listener.php', 'language/en/common.php', 'controller/main.php', 'styles/prosilver/template/demo_body.html']
        tags:
            - { name: phpbb.skeleton.ext.skeleton }

    phpbb.skeleton.ext.skeleton.tests:
        class: phpbb\skeleton\skeleton
        arguments:
            - 'tests'
            - true
            - []
            - ['tests/controller/main_test.php', 'tests/dbal/fixtures/config.xml', 'tests/dbal/simple_test.php', 'tests/functional/demo_test.php', 'tests/mock/controller_helper.php', 'tests/mock/template.php', 'tests/mock/user.php', 'phpunit.xml.dist']
        tags:
            - { name: phpbb.skeleton.ext.skeleton }

    phpbb.skeleton.ext.skeleton.travis:
        class: phpbb\skeleton\skeleton
        arguments:
            - 'travis'
            - true
            - ['tests']
            - ['travis/prepare-phpbb.sh', '.travis.yml']
        tags:
            - { name: phpbb.skeleton.ext.skeleton }
